language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "iojs"
notifications:
  email:
    on_success: change
    on_failure: change
sudo: false # use container based environment
